# Generated by Django 3.1.7 on 2021-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('gametype', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('summonerId', models.CharField(max_length=100)),
                ('accountId', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('profileIconId', models.SmallIntegerField()),
                ('summonerLevel', models.SmallIntegerField()),
                ('solo_rank', models.SmallIntegerField(default=0)),
                ('solo_rank_win', models.SmallIntegerField(default=0)),
                ('solo_rank_loss', models.SmallIntegerField(default=0)),
                ('flex_rank', models.SmallIntegerField(default=0)),
                ('flex_rank_win', models.SmallIntegerField(default=0)),
                ('flex_rank_loss', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
